name: CI
jobs: 
  getName:
  - name: Get target branch name
      id: target_branch
      run: echo "::set-output name=target_branch::${{ github.event.pull_request.base.ref }}"

on:
  pull_request:
    branches:
      - ${{ steps.target_branch.outputs.target_branch }} # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

